# Generated by Django 5.0.2 on 2024-03-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes_Mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.CharField(max_length=20),
        ),
    ]
