# Generated by Django 5.0.2 on 2024-03-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes_Mascotas', '0002_alter_mascota_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.CharField(max_length=20),
        ),
    ]
