# Generated by Django 5.0.2 on 2024-03-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('detalles', models.TextField()),
                ('prueba_diagnostica', models.TextField()),
                ('diagnostico_diferencial', models.CharField(max_length=100)),
                ('diagnostico_definitivo', models.CharField(max_length=100)),
                ('pronostico', models.CharField(max_length=100)),
                ('seguimiento', models.CharField(max_length=100)),
                ('temperatura_corporal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField()),
                ('peso_examen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones_examen', models.TextField()),
                ('receta_medica', models.TextField()),
                ('mascota', models.CharField(max_length=100)),
            ],
        ),
    ]
