# Generated by Django 5.0.2 on 2024-03-12 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes_Mascotas', '0003_alter_mascota_peso'),
        ('Historiales_clinicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes_Mascotas.mascota'),
        ),
    ]
