# Generated by Django 5.0.2 on 2024-03-12 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historiales_clinicos', '0002_alter_consulta_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
