# Generated by Django 5.0.2 on 2024-03-14 00:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes_Mascotas', '0004_alter_mascota_foto'),
        ('Historiales_clinicos', '0004_vacuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='desparasitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('nombre', models.CharField(max_length=100)),
                ('dosis', models.PositiveSmallIntegerField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes_Mascotas.mascota')),
            ],
        ),
    ]
