# Generated by Django 5.0.2 on 2024-03-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
